spring:

  application:
    name: velo

  config:
    import: "optional:file:.env[.properties]"

  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5430}/${DB_NAME}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6370}